### ISSUE TITLE
Add branch coverage _parse_sitemap

### ISSUE THREAD

**Issue by fliljeda** [aeakoski/scrapy#7]
Add branch coverage for function _parse_sitemap in file scrapy/spiders/sitemap.py

**Comment by dskeppstedt** [comment]
nvm

**Comment by dskeppstedt** [comment]
7/11 branches covered

**Comment by dskeppstedt** [comment]
These are not covered
https://github.com/aeakoski/scrapy/blob/75d5f798bbfa1fae61ab3195a56c5eea18b36fe0/scrapy/spiders/sitemap.py#L45-L49

https://github.com/aeakoski/scrapy/blob/75d5f798bbfa1fae61ab3195a56c5eea18b36fe0/scrapy/spiders/sitemap.py#L52-L58
